[tox]
envlist = py3.11, py3.12, py3.13

[testenv]
allowlist_externals = poetry
skip_install = true
ignore_errors = true
commands_pre = poetry install
commands = 
    poetry check
    black --diff --check src/diffpssi/ tests/
    isort --check-only src/diffpssi tests
    pydocstyle diffpssi tests
    ; pylint diffpssi tests
    ; mypy diffpssi tests
    ; pytest {posargs}
    poetry build

[pytest]
testpaths = tests

[coverage:run]
branch = True
source = src/diffpssi

[coverage:paths]
source = src/diffpssi

[coverage:report]
show_missing = True
