def load(
    tap_side="hv",
    measure_side="hv",
    trans_type="simple",
    trans_control="oltc",
    param_dict_oltc=None,
    B1=[400, 0],
    u_l=1,
    machine_size=2200,
    controllers=True,
):
    """
    Loads the grid data of the IBB transformer model.
    Returns: The grid data in form of a dictionary.

    """
    if controllers:
        return {
            "base_mva": 2200,
            "f": 60,
            "slack_bus": "B0",
            "base_voltage": 100,
            "busses": [
                ["name", "V_n"],
                ["B0", 10],
                ["B1", 100],
            ],
            "transformers": [
                [
                    "type",
                    "control",
                    "name",
                    "from_bus",
                    "to_bus",
                    "S_n",
                    "V_n_from",
                    "V_n_to",
                    "tap_side",
                    "measure_side",
                    "R",
                    "X",
                    "u_l",
                    "theta",
                    "param_dict_oltc",
                ],
                [
                    trans_type,
                    trans_control,
                    "T1",
                    "B0",
                    "B1",
                    2200,
                    10,
                    100,
                    tap_side,
                    measure_side,
                    0,
                    0.15,
                    u_l,
                    0,
                    param_dict_oltc,
                ],
            ],
            "generators": {
                "GEN": [
                    [
                        "name",
                        "bus",
                        "S_n",
                        "V_n",
                        "P",
                        "V",
                        "H",
                        "D",
                        "X_d",
                        "X_q",
                        "X_d_t",
                        "X_q_t",
                        "X_d_st",
                        "X_q_st",
                        "T_d0_t",
                        "T_q0_t",
                        "T_d0_st",
                        "T_q0_st",
                    ],
                    [
                        "G1",
                        "B0",
                        machine_size,
                        10,
                        -1998,
                        1,
                        3.5,
                        0,
                        1.81,
                        1.76,
                        0.3,
                        0.65,
                        0.23,
                        0.23,
                        8.0,
                        1,
                        0.03,
                        0.07,
                    ],
                ]
            },
            "loads": {
                "ZIP": [
                    ["name", "bus", "P", "Q", "model"],
                    ["L1", "B1", B1[0], B1[1], "Z"],
                ],
            },
            "gov": {
                "TGOV1": [
                    ["name", "gen", "R", "D_t", "V_min", "V_max", "T_1", "T_2", "T_3"],
                    ["GOV1", "G1", 0.05, 0.02, 0, 1, 0.5, 2, 2],
                ]
            },
            "avr": {
                "SEXS": [
                    ["name", "gen", "K", "T_a", "T_b", "T_e", "E_min", "E_max"],
                    ["AVR1", "G1", 100, 4.0, 10.0, 0.1, -10, 10],
                ]
            },
            "pss": {
                "STAB1": [
                    ["name", "gen", "K", "T", "T_1", "T_2", "T_3", "T_4", "H_lim"],
                    ["PSS1", "G1", 50, 10.0, 0.5, 0.5, 0.05, 0.05, 0.03],
                ]
            },
        }
    else:
        return {
            "base_mva": 2200,
            "f": 60,
            "slack_bus": "B0",
            "base_voltage": 100,
            "busses": [
                ["name", "V_n"],
                ["B0", 10],
                ["B1", 100],
            ],
            "transformers": [
                [
                    "type",
                    "control",
                    "name",
                    "from_bus",
                    "to_bus",
                    "S_n",
                    "V_n_from",
                    "V_n_to",
                    "tap_side",
                    "measure_side",
                    "R",
                    "X",
                    "u_l",
                    "theta",
                    "param_dict_oltc",
                ],
                [
                    trans_type,
                    trans_control,
                    "T1",
                    "B0",
                    "B1",
                    2200,
                    10,
                    100,
                    tap_side,
                    measure_side,
                    0,
                    0.15,
                    u_l,
                    0,
                    param_dict_oltc,
                ],
            ],
            "generators": {
                "GEN": [
                    [
                        "name",
                        "bus",
                        "S_n",
                        "V_n",
                        "P",
                        "V",
                        "H",
                        "D",
                        "X_d",
                        "X_q",
                        "X_d_t",
                        "X_q_t",
                        "X_d_st",
                        "X_q_st",
                        "T_d0_t",
                        "T_q0_t",
                        "T_d0_st",
                        "T_q0_st",
                    ],
                    [
                        "G1",
                        "B0",
                        machine_size,
                        10,
                        -1998,
                        1,
                        3.5,
                        0,
                        1.81,
                        1.76,
                        0.3,
                        0.65,
                        0.23,
                        0.23,
                        8.0,
                        1,
                        0.03,
                        0.07,
                    ],
                ]
            },
            "loads": {
                "ZIP": [
                    ["name", "bus", "P", "Q", "model"],
                    ["L1", "B1", B1[0], B1[1], "Z"],
                ],
            },
        }
