name: Test and Lint Code

on:
  push:
    branches:
      - main
      - release/*
      - development
      - feature/*
      - bugfix/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - release/*
      - development

jobs:
  pre-commit-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.4
          poetry install

      - name: Run code checks
        run: |
          poetry check
          poetry run black --diff --check src/diffpssi/ tests/
          poetry run isort --check-only src/diffpssi tests
          poetry run pydocstyle diffpssi tests
  
      - name: Run tests
        run: |
          poetry run pytest tests/*
  